// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_aykWLmTpc1fx6c3f6bZfb7KjH7sY8HE',
    appId: '1:714976219659:android:cc4623936070212e022d0e',
    messagingSenderId: '714976219659',
    projectId: 'mecl-chatbot',
    storageBucket: 'mecl-chatbot.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU011zFGNbIRRZhGheRIepyn6OvSMjZBo',
    appId: '1:714976219659:web:26088d88a7f60a8c022d0e',
    messagingSenderId: '714976219659',
    projectId: 'mecl-chatbot',
    authDomain: 'mecl-chatbot.firebaseapp.com',
    storageBucket: 'mecl-chatbot.appspot.com',
    measurementId: 'G-3DGDCNZ7FB',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU011zFGNbIRRZhGheRIepyn6OvSMjZBo',
    appId: '1:714976219659:web:a007e5d351210d14022d0e',
    messagingSenderId: '714976219659',
    projectId: 'mecl-chatbot',
    authDomain: 'mecl-chatbot.firebaseapp.com',
    storageBucket: 'mecl-chatbot.appspot.com',
    measurementId: 'G-3X68V9DHQ5',
  );

}